name: Greetings

on:
  pull_request_target:
    types: [closed]

jobs:
  congratulate:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Congratulate on every PR merge
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @${{ github.event.pull_request.user.login }} <h3>Hurray! Your PR has been merged! 🥳</h3> Thank you so much for your contribution during <strong>Hacktoberfest 💖</strong>!
Feel free to take on another issue 💖. We appreciate your support!