name: Star Check

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened]

jobs:
  check_star:
    runs-on: ubuntu-latest
    steps:
      - name: Check if repository is starred
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const user = context.payload.sender.login;

            // Check if the repo is starred by the user
            const response = await github.request('GET /user/starred/{owner}/{repo}', {
              owner: owner,
              repo: repo,
              headers: {
                authorization: `token ${process.env.GITHUB_TOKEN}`
              }
            });

            if (response.status !== 204) {
              const message = "Please star this repository before opening an issue or pull request.";
              await github.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: message,
              });
              // Optionally close the issue or pull request
              // await github.issues.update({
              //   ...context.repo,
              //   issue_number: context.issue.number,
              //   state: 'closed',
              // });
            }
